version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    command: --max-allowed-packet=256M
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    volumes:
      - ./txtler:/app/txtler

volumes:
  mysql_data:
